(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var m0=function(a){a.X("cardstatechange",a.Vh()&&a.Ul()?1:0)},n0=function(a,b){var c=g.Oa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},vVa=function(a){var b=g.il(a);
a=g.ll(a);return new g.Yk(b.x,b.y,a.width,a.height)},wVa=function(a){return Math.pow(a,3)},xVa=function(a){return 3*a*a-2*a*a*a},q0=function(a){a=g.Ra(a);
delete o0[a];g.Se(o0)&&p0&&p0.stop()},zVa=function(){p0||(p0=new g.K(function(){yVa()},20));
var a=p0;a.isActive()||a.start()},yVa=function(){var a=g.Ua();
g.Ie(o0,function(b){AVa(b,a)});
g.Se(o0)||zVa()},r0=function(a,b,c,d){g.po.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.N=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.D=null},AVa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.D);a.D=b;BVa(a,a.progress);1==a.progress?(a.j=0,q0(a),a.onFinish(),a.Vy()):a.Kc()&&a.NE()},BVa=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.N[c]-a.u[c])*b+a.u[c]},CVa=function(a,b){g.Ce.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},s0=function(a,b,c,d,e){r0.call(this,b,c,d,e);
this.element=a},t0=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
s0.call(this,a,b,c,d,e)},u0=function(a){g.I.call(this);
this.u=a||window;this.j=[]},v0=function(a){return a.baseUrl||null},w0=function(a,b){return g.cm(g.kk(a,b),function(c){return!!c})},DVa=function(a,b,c){function d(ba){var qa=ba.hovercardButton;
if(!qa)return null;qa=qa.subscribeButtonRenderer;if(!qa)return null;var fb=f(qa.unsubscribedButtonText),bb=f(qa.subscribedButtonText);if(qa.subscribed){var ub=f(qa.subscriberCountWithUnsubscribeText);var vb=f(qa.subscriberCountText)}else ub=f(qa.subscriberCountText),vb=f(qa.subscriberCountWithSubscribeText);var tc=null;if(ba.signinEndpoint){tc=n0(ba,"signinEndpoint","webNavigationEndpointData","url");if(!tc){var kb,Sb,Cb;tc=null==(kb=qa.signInEndpoint)?void 0:null==(Sb=kb.commandMetadata)?void 0:
null==(Cb=Sb.webCommandMetadata)?void 0:Cb.url}if(!tc)return null}return fb&&(bb||tc)?{subscribed:qa.subscribed,subscribeText:fb,subscribeCount:ub,unsubscribeText:bb,unsubscribeCount:vb,enabled:qa.enabled,signinUrl:tc,classic:ba.useClassicSubscribeButton}:null}
function e(ba){if(ba){var qa=[],fb=ba.videoId;fb&&qa.push("v="+fb);(fb=ba.playlistId)&&qa.push("list="+fb);(ba=ba.startTimeSeconds)&&qa.push("t="+ba);return"/watch?"+qa.join("&")}}
function f(ba){if(!ba)return null;var qa=ba.simpleText;return qa?qa:ba.runs?g.kk(ba.runs,function(fb){return fb.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,t=null,u=null,x=null,y=!1,z=null,D=null,H=null,G=null,L=null,aa=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:(aa=l.watchEndpoint,m=e(aa)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,t=f(p.text),p="LIVE"===p.style):t=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:(aa=l.watchEndpoint,m=e(aa)),n=!1,q=a,u=f(b.playlistLength);
else if("CHANNEL"===h){if(y=n0(l,"browseEndpoint","browseId"))x=y,m="/channel/"+x;n=!1;q="new";(y=!!b.isSubscribe)?z=d(b):D=f(b.subscribersText)}else"WEBSITE"===h?((H=n0(l,"urlEndpoint","url"))&&(m=H),n=!0,q="new",H=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=n0(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=n0(b,"title","accessibility","accessibilityData","label");var M=b.endpoint?b.endpoint.clickTrackingParams:
null,sa="";if(b.metadata){var za=f(b.metadata);za&&(sa=za)}return{id:"element-"+c,type:h,title:f(b.title),metadata:sa,callToAction:f(b.callToAction),pN:b.image,iconUrl:H,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:t,isLiveVideo:p,playlistLength:u,channelId:x,subscribeButton:z,subscribersText:D,isSubscribe:y,targetUrl:m||null,dX:n,sessionData:M?{itct:M}:null,O0:q,
ex:a?a:null,isPlaceholder:b.isPlaceholder,impressionUrls:w0(b.impressionUrls||[],v0),SW:w0(b.hovercardShowUrls||[],v0),clickUrls:w0(l.loggingUrls||[],v0),visualElement:g.Eu(b.trackingParams),productPrice:G,additionalFeesText:L,watchEndpoint:aa||null}},x0=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:w0(a.impressionUrls||[],v0),elements:w0(a.elements||[],function(d,e){return DVa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Eu(a.trackingParams));return c},y0=function(a){g.WI.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.V=!0;this.I=0;a=a.S();this.N=g.dB(a)||g.hB(a);this.W=a.experiments.fb("web_rounded_thumbnails");this.events=new g.kz(this);g.J(this,this.events);this.events.P(this.player,g.Cv("creatorendscreen"),this.onCueRangeEnter);this.events.P(this.player,g.Dv("creatorendscreen"),this.onCueRangeExit);this.events.P(this.player,"resize",this.wb);this.events.P(window,"focus",this.L_);this.load();var b=g.zg("STYLE");(g.og("HEAD")[0]||
document.body).appendChild(b);g.Be(this,function(){g.Dg(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},EVa=function(a){return a.player.getVideoData().D?"current":a.N?"new":"current"},z0=function(a){return"creator-endscreen-editor"===a.player.S().playerStyle},FVa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=x0(f,EVa(a))));A0(a,f)},
urlParams:{v:c},withCredentials:!0};a.N&&(c.urlParams.ptype="embedded");var d=b.Pr;d&&(c.postParams={ad_tracking:d});if(b=g.Sxa(b))if(b=g.Gf(b),b=g.Ef(b))a.B=g.pq(b,c)},A0=function(a,b,c){c=void 0===c?!0:c;
a.player.Df("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&GVa(a);c=[];d=new g.Av(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.S().isMobile||(a.u=new g.W({F:"div",L:"ytp-ce-shadow"}),g.II(a.player,a.u.element,4),a.C=new g.hH(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=HVa(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.II(a.player,f.element,4);var h=new g.Av(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);IVa(a,
f,e)}else g.Bu(new g.Ar("buildEndscreenElement null",e))}a.player.Vd(c);a.wb()}},GVa=function(a){var b=g.Ku(),c=g.Lu();
c&&b&&a.endscreen.visualElement&&g.Pu(void 0,c,b,[a.endscreen.visualElement])},HVa=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={F:"div",Ba:["ytp-ce-element","ytp-ce-video"],T:{tabindex:"0","aria-label":b.ex||"","aria-hidden":"true"},R:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-covering-image",T:B0(b)},{F:"div",L:"ytp-ce-covering-shadow-top"},{F:"a",L:"ytp-ce-covering-overlay",T:{href:C0(a,b.targetUrl),tabindex:"-1"},R:[{F:"div",Ba:["ytp-ce-video-title","ytp-webkit-ellipsis"],T:{dir:g.to(b.title||"")},Z:b.title},{F:"div",L:b.isLiveVideo?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
Z:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={F:"div",Ba:["ytp-ce-element","ytp-ce-playlist"],T:{tabindex:"0","aria-label":b.ex||"","aria-hidden":"true"},R:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-covering-image",T:B0(b)},{F:"div",L:"ytp-ce-covering-shadow-top"},{F:"a",L:"ytp-ce-covering-overlay",T:{href:C0(a,b.targetUrl),tabindex:"-1"},R:[{F:"div",Ba:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],T:{dir:g.to(b.title||"")},Z:b.title},{F:"div",L:"ytp-ce-playlist-count",
R:[{F:"div",L:"ytp-ce-playlist-icon"},{F:"div",L:"ytp-ce-playlist-count-text",Z:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={F:"div",Ba:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],T:{tabindex:"0","aria-label":b.ex||"","aria-hidden":"true"},R:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-expanding-overlay",R:[{F:"div",L:"ytp-ce-expanding-overlay-hider"},{F:"div",L:"ytp-ce-expanding-overlay-background"},{F:"div",L:"ytp-ce-expanding-overlay-content",
R:[{F:"div",L:"ytp-ce-expanding-overlay-body",R:[{F:"div",L:"ytp-ce-expanding-overlay-body-padding",R:[{F:"a",Ba:["ytp-ce-channel-title","ytp-ce-link"],T:{href:C0(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.to(b.title||"")},Z:b.title},b.subscribeButton?{F:"div",L:"ytp-ce-subscribe-container",R:[{F:"div",L:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{F:"div",L:"ytp-ce-channel-subscribers-text",Z:b.subscribersText}:"",b.metadata?{F:"div",Ba:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],Z:b.metadata}:""]}]}]}]},{F:"div",L:"ytp-ce-expanding-image",T:B0(b)}]};c=new g.W(c);var d=g.pg(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.N(d,"ytp-ce-subscribe-button");if(a.player.S().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.aK(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,
!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={F:"div",Ba:["ytp-ce-element","ytp-ce-website"],T:{tabindex:"0","aria-label":b.ex||"","aria-hidden":"true"},R:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-expanding-overlay",R:[{F:"div",L:"ytp-ce-expanding-overlay-hider"},{F:"div",L:"ytp-ce-expanding-overlay-background"},{F:"div",L:"ytp-ce-expanding-overlay-content",
R:[{F:"div",L:"ytp-ce-expanding-overlay-body",R:[{F:"div",L:"ytp-ce-expanding-overlay-body-padding",R:[{F:"div",L:"ytp-ce-website-title",T:{dir:g.to(b.title||"")},Z:b.title},{F:"div",L:"ytp-ce-website-metadata",Z:b.metadata},{F:"a",Ba:["ytp-ce-website-goto","ytp-ce-link"],T:{href:C0(a,b.targetUrl),target:"_blank",tabindex:"-1"},Z:b.callToAction}]}]}]}]},{F:"div",L:"ytp-ce-expanding-image",T:B0(b)},{F:"div",L:"ytp-ce-expanding-icon",T:JVa(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c=
"",b.productPrice&&(c={F:"div",L:"ytp-ce-merchandise-price-container",R:[{F:"div",L:"ytp-ce-merchandise-price",Z:b.productPrice}]},b.additionalFeesText&&c.R.push({F:"div",L:"ytp-ce-merchandise-additional-fees",Z:b.additionalFeesText})),a={F:"div",Ba:["ytp-ce-element","ytp-ce-merchandise"],T:{tabindex:"0","aria-label":b.ex||"","aria-hidden":"true"},R:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-expanding-overlay",R:[{F:"div",L:"ytp-ce-expanding-overlay-hider"},{F:"div",L:"ytp-ce-expanding-overlay-background"},
{F:"div",L:"ytp-ce-expanding-overlay-content",R:[{F:"div",L:"ytp-ce-expanding-overlay-body",R:[{F:"div",L:"ytp-ce-expanding-overlay-body-padding",R:[{F:"div",L:"ytp-ce-merchandise-title",T:{dir:g.to(b.title||"")},Z:b.title},c,{F:"div",L:"ytp-ce-merchandise-metadata",Z:b.metadata},{F:"a",Ba:["ytp-ce-merchandise-goto","ytp-ce-link"],T:{href:C0(a,b.targetUrl),target:"_blank",tabindex:"-1"},Z:b.callToAction}]}]}]}]},{F:"div",L:"ytp-ce-expanding-image",T:B0(b)},{F:"div",L:"ytp-ce-merchandise-invideo-cta-container",
R:[{F:"div",L:"ytp-ce-merchandise-invideo-cta",Z:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.N(c.element,"ytp-ce-placeholder");return c},B0=function(a){if(a.pN)var b=a.pN.thumbnails;
return JVa(b?b[b.length-1].url:null)},JVa=function(a){return a?{style:"background-image: url("+a+")"}:{}},IVa=function(a,b,c){function d(m){m&&(b.Ma("blur",function(){"none"!=m.style.display&&a.V&&m.focus()}),b.P(m,"focus",f),b.P(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.N(b.element,"ytp-ce-force-expand"),D0(a,c.id,!0)):(g.go(b.element,"ytp-ce-force-expand"),g.go(b.element,"ytp-ce-element-hover"),D0(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ma("mouseenter",function(){E0(a,b,c)});
b.Ma("mouseleave",function(){F0(a,b,c)});
a.player.S().isMobile||b.Ma("click",function(){g.N(b.element,"ytp-ce-element-hover")});
b.Ma("click",function(m){KVa(a,c,m)});
b.Ma("keypress",function(m){KVa(a,c,m)});
b.Ma("focus",function(){E0(a,b,c)});
b.Ma("blur",function(){F0(a,b,c)});
b.Ma("touchstart",function(){E0(a,b,c)});
var l=g.rg("ytp-ce-expanding-overlay-hider",b.element);l&&b.P(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.go(b.element,"ytp-ce-element-hover");g.go(b.element,"ytp-ce-force-expand")});
b.Ma("keydown",function(m){a.V=9===m.keyCode&&!m.shiftKey});
d(g.rg("ytp-sb-subscribe",b.element));d(g.rg("ytp-sb-unsubscribe",b.element));b.Ma("focus",f);b.Ma("blur",h)},KVa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.eo(d,"ytp-ce-element");){g.eo(d,"subscribe-label")&&G0(a,b);
if(g.eo(d,"ytp-ce-channel-subscribe"))return;d=g.Eg(d)}if(!d||g.eo(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])F0(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.O0)G0(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Gf(C0(a,b.targetUrl)),g.HH(g.Ef(c),void 0,b.sessionData);else{var e=g.SB(a.player.S())||a.player.getVideoData().D,f=function(){var h=C0(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.bq(h);e&&n&&(n.v||n.list)?
a.player.vl(n.v,l,n.list,!1,void 0,m||void 0):g.GH(h,l)};
G0(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},C0=function(a,b){a=a.player.S();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.bC(a)+b}else return"";return b},E0=function(a,b,c){g.eo(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.N(b.element,"ytp-ce-element-hover"):a.player.S().isMobile?(new g.K(function(){g.N(b.element,"ytp-ce-element-hover")},200)).start():g.N(b.element,"ytp-ce-element-hover"),H0(a,c.SW),D0(a,c.id,!0))},F0=function(a,b,c){g.go(b.element,"ytp-ce-element-hover");
g.go(b.element,"ytp-ce-force-expand");D0(a,c.id,!1)},D0=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.O(a.j[e].element,"ytp-ce-element-shadow-show",c)},H0=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||z0(a))c&&c();else{b=LVa(a,b);var e=0,f=!1,h=new g.K(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Gs(b[a],d)}},G0=function(a,b,c){H0(a,b.clickUrls,c);
(a=g.Lu())&&b.dX&&g.Vu(a,b.visualElement)},LVa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(MVa(b[d],c));return a},MVa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},NVa=function(a){return"string"===typeof a?a:""},I0=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},OVa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},J0=function(a){return a.value?a.value:null},K0=function(a){if(!a)return null;
var b=g.Gf(NVa(a.value));b=g.Ef(b);if(!b)return null;var c=I0(a.target,PVa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new OVa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},QVa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},TVa=function(a){if(!a)return null;
var b=I0(a.type,RVa),c=I0(a.trigger,SVa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=K0(a?a:null);return b?new QVa(b,c,a):null},UVa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},WVa=function(a){return(a=VVa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},VVa=function(a,b){return g.Ub(a.action,b)},XVa=function(a,b){this.context=a;
this.j=b},M0=function(a){return a.customMessage?L0("div","iv-card-message",a.customMessage):""},N0=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{F:"div",L:"iv-card-image",T:{style:a},R:c}},O0=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(L0("li","",c.value));return{F:"ul",L:"iv-card-meta-info",R:b}},L0=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.to(c);return{F:a,T:b,Z:c}},YVa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.ox&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.ox+");");c.dir=g.to(a.customMessage);var d=[{F:"span",Z:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({F:"span",L:"iv-card-link-icon"}));return{F:"div",Ba:b,T:c,R:d}},P0=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},ZVa=function(a,b){this.merchant=a;
this.price=b},$Va=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},aWa=function(a,b){return b?b:$Va(a)?"current":"new"},Q0=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.kb=!1;this.Sa=new Map;this.Ta=new Map;this.context.G.addEventListener(g.Cv("annotations_module"),function(d){(d=c.Sa.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.Dv("annotations_module"),function(d){(d=c.Ta.get(d))&&d.apply(c)})},R0=function(a,b,c,d,e,f,h){a.context.j.Ma(b,"click",function(l){a.OE(c,d,e,f||[],h||0,l)});
a.context.j.Ma(b,"touchstart",function(){a.kb=!1});
a.context.j.Ma(b,"touchmove",function(){a.kb=!0})},bWa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},S0=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
BR:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
BD:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},V0=function(a,b,c){Q0.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.Ia=this.Kb=this.B=this.isInitialized=!1;this.ma=null;this.cards=[];this.qb=this.N=this.Ga=this.D=this.Pa=this.j=null;this.W=[];this.Y=this.J=this.jf=this.Da=null;this.I=0;this.va=new g.K(function(){},c.U.bf?4E3:3E3);
g.J(this,this.va);this.eb=new g.K(function(){});
g.J(this,this.eb);this.oa=new XVa(c,function(e,f,h,l,m,n){R0(d,e,f,h,l,m,n)});
this.V=new g.W({F:"div",L:"iv-drawer",T:{id:"iv-drawer"},R:[{F:"div",L:"iv-drawer-header",T:{"aria-role":"heading"},R:[{F:"span",L:"iv-drawer-header-text"},{F:"button",Ba:["iv-drawer-close-button","ytp-button"],T:{"aria-label":"Hide cards",tabindex:"0"}}]},{F:"div",L:"iv-drawer-content"}]});g.J(this,this.V);this.C=this.V.element;this.bb=new g.hH(this.V,330);g.J(this,this.bb);this.Ib=g.rg("iv-drawer-header-text",this.C);this.u=g.rg("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Kb&&T0(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Kb=d.B)&&U0(d)});
this.G.addEventListener("videodatachange",this.Ep.bind(this))},cWa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){T0(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){U0(a)});
var c=b.headerText;g.Gg(a.Ib,c);a.N&&a.N.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Da=g.Eu(b.trackingParams);a.J=g.Eu(b.closeTrackingParams);a.jf=g.Eu(b.iconTrackingParams)},dWa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.G.S().experiments.fb("enable_error_corrections_infocard");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){d=b.teaser.simpleCardTeaserRenderer;var e=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.Hv(d.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,tracking:{},Vl:null,jj:d.trackingParams?g.Eu(d.trackingParams):null,jf:e&&e.trackingParams?g.Eu(e.trackingParams):null,imageUrl:"",displayDomain:null,
showLinkIcon:!1,ox:null,title:"",customMessage:"",url:null,onClickCommand:d.onTapCommand||null};W0(a,b)}else if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.Hv(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:X0(a,
c,b,d),sponsored:!1,tracking:S0(d,e,d.command),Vl:d.trackingParams?g.Eu(d.trackingParams):null,jj:e.trackingParams?g.Eu(e.trackingParams):null,jf:f&&f.trackingParams?g.Eu(f.trackingParams):null,imageUrl:Y0(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.Hv(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,ox:null,title:d.title?g.Hv(d.title):"",customMessage:d.callToAction?g.Hv(d.callToAction):"",url:d.command.urlEndpoint.url?K0({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:d.command.urlEndpoint.url}):null,onClickCommand:null};W0(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.Hv(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:X0(a,
c,b,d),sponsored:!1,tracking:S0(d,e,d.endpoint),Vl:d.trackingParams?g.Eu(d.trackingParams):null,jj:e.trackingParams?g.Eu(e.trackingParams):null,jf:f&&f.trackingParams?g.Eu(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.Hv(d.customText):null,profileImageUrl:Y0(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.Hv(d.channelName):"",metaInfo:[d.subscriberCountText?g.Hv(d.subscriberCountText):""],url:K0({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId}),onClickCommand:null};W0(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.Hv(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:X0(a,c,b,d),sponsored:!1,tracking:S0(d,e,d.action),Vl:d.trackingParams?g.Eu(d.trackingParams):null,jj:e.trackingParams?g.Eu(e.trackingParams):null,jf:f&&f.trackingParams?g.Eu(f.trackingParams):null,Pz:Y0(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.Hv(d.customMessage):null,playlistVideoCount:g.Hv(d.playlistVideoCount),title:d.playlistTitle?g.Hv(d.playlistTitle):"",metaInfo:[d.channelName?
g.Hv(d.channelName):"",d.videoCountText?g.Hv(d.videoCountText):""],url:K0({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:bWa(d.action)}),onClickCommand:null};W0(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.Hv(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:X0(a,c,b,d),sponsored:!1,tracking:S0(d,e,d.action),Vl:d.trackingParams?g.Eu(d.trackingParams):null,jj:e.trackingParams?g.Eu(e.trackingParams):null,jf:f&&f.trackingParams?g.Eu(f.trackingParams):null,Pz:Y0(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.Hv(d.lengthString):null,customMessage:d.customMessage?g.Hv(d.customMessage):null,title:d.videoTitle?g.Hv(d.videoTitle):"",metaInfo:[d.channelName?
g.Hv(d.channelName):"",d.viewCountText?g.Hv(d.viewCountText):""],isLiveNow:!!d.badge,url:K0({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:bWa(d.action)}),onClickCommand:null};W0(a,b)}a.I++},Y0=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},X0=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},fWa=function(a,b){if(b=eWa(a,b))b===a.j&&(a.j=null),a.G.removeCueRange(b.card.id),g.Dg(b.JF),g.bc(a.cards,b),a.OA(),Z0(a)},T0=function(a,b,c){if(!a.B){a.bb.show();
a.Pa=new g.K(function(){g.N(a.context.G.getRootNode(),g.zO.IV_DRAWER_OPEN)},0);
a.Pa.start();a.ma=g.ht(a.u,"mousewheel",function(h){a.va.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.Lu();d&&a.Da&&a.J&&g.Tu(d,[a.Da,a.J]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.aP||(f.aP=!0,gWa(a.context.logger,f.card.tracking.impression,b)),d&&g.Tu(d,[f.card.Vl]);m0(a.G);c&&(a.D=new g.K(function(){a.Ga=a.N;a.qb.focus()},330),a.D.start())}},U0=function(a){a.B&&(a.bb.hide(),g.jt(a.ma),a.ma=null,g.go(a.context.G.getRootNode(),g.zO.IV_DRAWER_OPEN),a.B=!1,m0(a.G),a.D&&a.D.stop(),a.D=new g.K(function(){a.Ga&&(a.Ga.focus(),a.Ga=null)},330),a.D.start())},
iWa=function(a){g.fo(a.element,[g.zO.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.II(a.G,a.C,5);hWa(a);a.N=g.rg("ytp-cards-button",a.G.getRootNode());a.qb=g.rg("iv-drawer-close-button",a.C);a.isInitialized=!0},hWa=function(a){var b=g.rg("iv-drawer-close-button",a.C);
a.context.j.Ma(b,"click",a.AV,a);a.context.j.Ma(a.u,"touchend",function(){a.va.start()});
a.context.j.Ma(a.u,"scroll",a.NV,a);a.context.u.subscribe("onHideControls",function(){a.Ia=!0});
a.context.u.subscribe("onShowControls",function(){a.Ia=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ia=g.eo(a.G.getRootNode(),"ytp-autohide")});
a.W.push(g.Dt("iv-button-shown",a.mX,a));a.W.push(g.Dt("iv-button-hidden",a.lX,a));a.W.push(g.Dt("iv-teaser-shown",a.uU,a));a.W.push(g.Dt("iv-teaser-hidden",a.nX,a));a.W.push(g.Dt("iv-teaser-clicked",a.tU,a))},jWa=function(a,b){var c,d=null==(c=a.G.getVideoData())?void 0:c.multiMarkersPlayerBarRenderer;
if(null==d?0:d.markersMap){var e;for(c=0;(null==(e=d)?void 0:e.markersMap.length)>c;c++){var f=void 0,h=null==(f=d)?void 0:f.markersMap[c];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=h[0].markerRenderer)?void 0:d.timeRangeStartMillis)||0,a.Y=null,!0}}a.Y=b;return!1},W0=function(a,b){if(b.onClickCommand&&b.onClickCommand.changeEngagementPanelVisibilityAction&&"engagement-panel-error-corrections"===b.onClickCommand.changeEngagementPanelVisibilityAction.targetId){a.Y=
b;
var c=!0}else c=!1;if(!c||jWa(a,b))if(c=kWa(a,b)){var d={card:b,JF:c.element,aP:!1};if(!b.onClickCommand){a.isInitialized||iWa(a);fWa(a,b.id);var e=lWa(a,d);g.hc(a.cards,e,0,d);c.xa(a.u,e);a.OA()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,Z0(a),mWa(a,d),T0(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&nWa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){nWa(a,d)}),Z0(a))}},kWa=function(a,b){switch(b.type){case "simple":a=
a.oa;
var c=b.displayDomain?{F:"div",L:"iv-card-image-text",Z:b.displayDomain}:void 0;var d=YVa(b);c={F:"div",Ba:["iv-card"],R:[{F:"a",L:"iv-click-target",T:{href:b.url?J0(b.url)||"":""},R:[N0(b.imageUrl,c),{F:"div",L:"iv-card-content",R:[L0("h2",void 0,b.title),d]}]}]};c=new g.W(c);P0(a,g.qg("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.oa,c={F:"div",Ba:["iv-card","iv-card-channel"],R:[{F:"a",Ba:["iv-click-target"],T:{href:J0(b.url)||"","data-ytid":b.channelId},R:[N0(b.profileImageUrl),
{F:"div",L:"iv-card-content",R:[M0(b),{F:"h2",L:"iv-card-primary-link",Z:b.title},O0(b)]}]}]},c=new g.W(c),P0(a,g.qg("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.oa,c={F:"div",Ba:["iv-card","iv-card-playlist"],R:[{F:"a",L:"iv-click-target",T:{href:J0(b.url)||""},R:[N0(b.Pz,{F:"div",L:"iv-card-image-overlay",R:[{F:"span",L:"iv-card-playlist-video-count",Z:b.playlistVideoCount}]}),{F:"div",L:"iv-card-content",R:[M0(b),L0("h2","iv-card-primary-link",b.title),O0(b)]}]}]},c=new g.W(c),
P0(a,g.qg("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.oa;var e=!g.Yb(b.offers);c=["iv-card"];d="";var f=YVa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({F:"div",L:"iv-card-offer-price",Z:f.price}),f.merchant&&e.push({F:"div",L:"iv-card-offer-merchant",Z:f.merchant}),f={F:"div",R:e});e=b.url?J0(b.url)||"":"";c={F:"div",Ba:c,T:{tabindex:"0"},R:[{F:"a",Ba:["iv-card-image","iv-click-target"],T:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{F:"div",L:"iv-card-content",R:[b.sponsored?{F:"div",L:"iv-card-sponsored",R:["Sponsored",{F:"div",L:"iv-ad-info-container",R:[{F:"div",L:"iv-ad-info",Z:"{{adInfo}}"},{F:"div",L:"iv-ad-info-icon-container",R:[{F:"div",L:"iv-ad-info-icon"},{F:"div",L:"iv-ad-info-callout"}]}]}]}:"",{F:"a",L:"iv-click-target",T:{href:e},R:[L0("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.zg("span");g.Gg(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Jd(d,"adInfo");P0(a,g.qg("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.oa,d=b.videoDuration?{F:"span",L:"iv-card-video-duration",Z:b.videoDuration}:void 0,f=b.isLiveNow?{F:"span",Ba:["yt-badge","yt-badge-live"],Z:"LIVE NOW"}:null,e={F:"div",Ba:["iv-card","iv-card-video"],R:[{F:"a",L:"iv-click-target",T:{href:(null==(c=b.url)?void 0:J0(c))||""},R:[N0(b.Pz,d),{F:"div",L:"iv-card-content",R:[M0(b),L0("h2","iv-card-primary-link",b.title),O0(b),f]}]}]},c=new g.W(e),P0(a,g.qg("iv-click-target",
c.element),b,b.url),c;default:return null}},lWa=function(a,b){if(0===a.cards.length)return 0;
a=g.Vb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},oWa=function(a){return a.j?"productListing"===a.j.card.type:g.lk(a.cards,function(b){return"productListing"===b.card.type})},Z0=function(a){g.O(a.G.getRootNode(),"ytp-cards-shopping-active",oWa(a))},nWa=function(a,b){if(!g.eo(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.Lu(),d=a.j?a.j.card.jf:a.jf;
c&&d&&g.Uu(c,[d]);a.j=b;Z0(a)}(c=a.isInitialized&&"none"==a.element.style.display)||(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=!(1===c||3===c||d));c||b.card.teaserDurationMs&&a.G.Pv(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs,onClickCommand:b.card.onClickCommand});a.eb.isActive()||((!a.B||!a.va.isActive()&&a.Ia)&&mWa(a,b),a.eb.start(910+b.card.teaserDurationMs))}},mWa=function(a,b){a.V.ob?(b=new r0([0,
a.u.scrollTop],[0,b.JF.offsetTop],600,xVa),a.context.B.Ma(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ma(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.wG(a.V,!0),a.u.scrollTop=b.JF.offsetTop,g.wG(a.V,!1))},$0=function(a){return a.j&&a.j.card?a.j.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},eWa=function(a,b){return g.Ub(a.cards,function(c){return c.card.id===b})},a1=function(a,b,c){Q0.call(this,a,b);
this.annotation=c;this.isActive=!1},pWa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},b1=function(a,b,c){a1.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},qWa=function(a,b){var c=void 0===c?0:c;
var d=vVa(b).width;g.gl(b,d);c=new t0(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,wVa);g.J(a,c);a.context.B.Ma(c,"begin",function(){g.ml(b,!0)});
c.play()},tWa=function(a,b){if(b.channel_name){var c=a.createElement({F:"div",
Ba:["iv-branding-context-name"],Z:b.channel_name}),d=a.createElement({F:"div",Ba:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.aK(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.G),a.j.xa(d));var f=a.createElement({F:"div",Ba:["iv-branding-context-subscribe-caret"]}),h=a.createElement({F:"div",Ba:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.ml(h,!1);var l=a.createElement({F:"div",Ba:["branding-context-container-outer"]});l.appendChild(h);g.al(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.K(function(){rWa(a,h,l)},500);
g.J(a,a.B);a.context.j.Ma(a.element,"mouseover",function(){sWa(a,h,l,f,b.image_height)});
a.context.j.Ma(a.element,"mouseout",function(){a.B.start()})}},sWa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.ll(b);a.j||(b.style.width=g.fl(f.width,!0),c.style.width=g.fl(f.width,!0));g.al(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.al(d,"right","1px");a.C=!0;g.ml(b,!0);a.D=new g.K(function(){g.N(this.element,"iv-branding-active")},0,a);
a.D.start()}},rWa=function(a,b,c){g.go(a.element,"iv-branding-active");
a.I=new g.K(function(){g.ml(b,!1);a.j||(c.style.width=g.fl(0,!0))},250);
a.I.start();a.C=!1},uWa=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.U=c;this.videoData=d;this.logger=e;this.G=f;this.u=h},c1=function(a,b,c){a1.call(this,a,b,c);
var d=this;this.N=this.isCollapsed=this.V=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({F:"div",Ba:["iv-promo-contents"]});this.D=new g.K(function(){d.j.setAttribute("aria-hidden","true");g.ml(d.B,!1);g.ml(d.u,!0)},700,this);
g.J(this,this.D)},vWa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=WVa(a.annotation),f=b.image_url;if(f){var h=a.createElement({F:"div",Ba:["iv-promo-img","iv-click-target"]});f=a.createElement({F:"img",T:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({F:"span",L:"iv-promo-video-duration",Z:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({F:"span",L:"iv-promo-playlist-length",Z:b.playlist_length.toString()}),h.appendChild(f));e&&R0(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({F:"a",L:"iv-promo-txt"}),g.Uf(f,J0(e)),a.j=f):a.j=a.createElement({F:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({F:"p",R:[{F:"strong",
Z:b.text_line_1}]});var m=a.createElement({F:"p",R:[{F:"span",L:"iv-promo-link",Z:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({F:"button",Ba:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({F:"button",Ba:["iv-button","iv-promo-button"],R:[{F:"span",L:"iv-button-content",Z:f}]});var p=a.createElement({F:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&R0(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.N(a.j,
"iv-click-target");e&&R0(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({F:"p",R:[{F:"span",Z:b.text_line_1}]}),m=a.createElement({F:"p",R:[{F:"strong",Z:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({F:"span",Ba:["yt-badge","iv-promo-badge-live"],Z:"LIVE NOW"})),g.N(a.j,"iv-click-target"),e&&R0(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);p&&a.J.appendChild(p);
c=a.createElement({F:"div",L:"iv-promo-actions"});a.u=a.createElement({F:"button",Ba:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.Ma(a.u,"click",function(q){d1(a,5E3,q)});
c.appendChild(a.u);g.ml(a.u,!1);a.context.j.Ma(a.element,"mouseover",a.tW,a);a.context.j.Ma(a.element,"mouseout",a.sW,a);a.context.j.Ma(a.element,"touchend",function(q){d1(a,5E3,q)});
a.B=a.createElement({F:"button",Ba:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.Ma(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.oW:a.nW,a);c.appendChild(a.B);g.fo(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},d1=function(a,b,c){c.stopPropagation();
wWa(a);xWa(a,b);a.j.focus()},yWa=function(a){a.isCollapsed||a.N||a.C||(g.N(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},wWa=function(a){a.D.stop();
a.isCollapsed&&(g.ho(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.ml(a.u,!1),g.ml(a.B,!0))},xWa=function(a,b){a.C||(a.C=g.$g(function(){e1(this);
yWa(this)},b,a))},e1=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},zWa=function(a){this.G=a},gWa=function(a,b,c){b&&(c?f1(a,b.map(function(d){return g.yn(d,c)})):f1(a,b))},f1=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Gs(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},g1=function(a){g.WI.call(this,a);
var b=this;this.loadNumber=0;this.I={};this.logger=new zWa(this.player);this.D=new g.kz(this);this.C=this.Om=null;this.events=new g.kz(this);this.J=this.j=null;this.N=[];g.J(this,this.D);this.D.P(this.player,"onVideoAreaChange",function(){b.X("onVideoAreaChange")});
this.D.P(this.player,"onHideControls",function(){b.X("onHideControls")});
this.D.P(this.player,"onShowControls",function(){b.X("onShowControls")});
this.D.P(this.player,"resize",function(d){b.X("resize",d)});
this.D.P(this.player,"presentingplayerstatechange",function(d){b.X("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.vU,this);this.subscribe("resize",this.FC,this);this.player.S().W.subscribe("vast_info_card_add",this.mQ,this);g.J(this,this.events);this.V=this.createElement({F:"div",L:"video-custom-annotations"});this.u=new g.W({F:"div",Ba:["ytp-player-content","ytp-iv-player-content"]});g.J(this,this.u);g.II(this.player,this.u.element,4);this.u.hide();this.B=new g.W({F:"div",Ba:["ytp-iv-video-content"]});g.J(this,this.B);a=this.createElement({F:"div",L:"video-annotations"});
a.appendChild(this.V);this.B.element.appendChild(a);this.Ms()&&this.load();var c=this.createElement({F:"style"});(g.og("HEAD")[0]||document.body).appendChild(c);g.Be(this,function(){g.Dg(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},AWa=function(a){a=a.createElement({F:"div",
Ba:["annotation","annotation-type-custom"]});g.ml(a,!1);return a},BWa=function(a,b){b=!b.isCued()&&!g.V(b,1024);
g.wG(a.u,b);g.wG(a.B,b)},CWa=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Pa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(CWa(a,e))}return c},FWa=function(a){var b=a.player.getVideoData();
if(b.Sa){var c=a.player.S().W.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.jq(h)&&h.responseXML?h.responseXML:null)&&h1(a,h)}};
g.or()&&(d.onFinish=DWa(a,d.onFinish));d.postParams={ic_only:"1"};EWa(d,c);g.pq(b.Sa,d)}}},EWa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.qx&&(a.postParams.ic_coll=b.qx);b.TA&&(a.postParams.ic_xml=b.TA);b.Tz&&(a.postParams.ic_track=b.Tz)},GWa=function(a){var b=new g.W({F:"div"});
g.ml(b.element,!1);var c=new V0(a.player,b.element,i1(a));g.J(c,b);b.xa(a.u.element);c.Dz();return c},i1=function(a){if(!a.J){var b=new u0(a);
g.J(a,b);var c=new g.ej(a);g.J(a,c);a.J=new uWa(b,c,a.player.S(),a.player.getVideoData(),a.logger,a.player,a.Le)}return a.J},h1=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Lu();if(e){var f=g.Ku();f&&g.Pu(void 0,e,f,[g.Eu(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=CWa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=I0(f.type,HWa),p=I0(f.style,IWa),q=NVa(f.data),t=0!==q.length?JSON.parse(q):{};var u=f.action;f=TVa;if(null==u)var x=null;else if(g.Oa(u)){l=[];for(var y=g.r(u),z=y.next();!z.done;z=y.next()){var D=f(z.value);
D&&l.push(D)}x=l}else{var H=f(u);x=H?[H]:[]}e=m&&n?new UVa(m,n,p,x,t):null}else e=null}catch(za){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var G=AWa(f),L=null;switch(l.type){case "branding":if(f.player.S().Nc)break;f.u.element.appendChild(G);L=new b1(G,i1(f),l);break;case "promotion":g.II(f.player,G,4),L=new c1(G,i1(f),l)}L&&L.Dz();if(f=L)g.J(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=GWa(a),g.J(a,a.j));if("card"===e.type){c=a.j;var aa=e&&e.data&&e.data.card_type;
f=e.data;if(aa)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,BR:l.teaser_impression,BD:l.teaser_click},G=f.tracking_params||{},L=null,aa){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Vl:G.card?g.Eu(G.card):null,jj:G.teaser?g.Eu(G.teaser):null,jf:G.icon?g.Eu(G.icon):
null,channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:K0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};W0(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,
Vl:G.card?g.Eu(G.card):null,jj:G.teaser?g.Eu(G.teaser):null,jf:G.icon?g.Eu(G.icon):null,Pz:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:K0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};W0(c,e);break;case "productListing":f.signin_url&&(L=K0({target:"current",value:f.signin_url}));aa=[];for(var M=f.offers||[],sa=0;sa<M.length;sa++)aa.push(new ZVa(g.ig(M[sa].merchant),
g.ig(M[sa].price)));e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Vl:G.card?g.Eu(G.card):null,jj:G.teaser?g.Eu(G.teaser):null,jf:G.icon?g.Eu(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,ox:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:K0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Pka:L,Oka:f.signin_title?f.signin_title:void 0,Nka:f.signin_message?f.signin_message:void 0,offers:aa,onClickCommand:null};W0(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Vl:G.card?g.Eu(G.card):
null,jj:G.teaser?g.Eu(G.teaser):null,jf:G.icon?g.Eu(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,ox:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:K0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};W0(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Vl:G.card?g.Eu(G.card):null,jj:G.teaser?g.Eu(G.teaser):null,jf:G.icon?g.Eu(G.icon):null,Pz:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:K0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},W0(c,e)}}else cWa(a.j,e);c=
!0}}c&&(m0(a.player),a.FC())},JWa=function(a,b){var c=!1;
a.j||(a.j=GWa(a),g.J(a,a.j));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(dWa(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.Hv(b.headerText):"",g.Gg(c.Ib,d),c.N&&c.N.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Da=b.trackingParams?g.Eu(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.Eu(b.closeButton.infoCardIconRenderer.trackingParams):null,c.jf=b.icon.infoCardIconRenderer.trackingParams?
g.Eu(b.icon.infoCardIconRenderer.trackingParams):null,m0(a.player),a.FC())},KWa=function(a,b,c,d,e){if(!a.player.S().Nc){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new QVa("openUrl","click",new OVa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.Hv(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.Hv(b.subscriberCountText))):(b.subscriberCountText&&(e=g.Hv(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.Hv(b.subscriberCountWithSubscribeText)));var m,n,p=(null==(l=b.signInEndpoint)?void 0:
null==(m=l.commandMetadata)?void 0:null==(n=m.webCommandMetadata)?void 0:n.url)||"";l={subscribeText:g.Hv(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.Hv(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=l}f=new UVa(c,"branding","branding",f,d);l=AWa(a);a.u.element.appendChild(l);f=new b1(l,i1(a),f);f.Dz();g.J(f,f);a.I[c]=f}},DWa=function(a,b){return function(){var c=
g.Ea.apply(0,arguments);
a.isDisposed()||a.N.push(g.Bn.Yg(function(){b.apply(null,g.v(c))}))}},LWa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.BI.prototype.Pv=g.ea(17,function(a,b){var c=g.mJ(this.ib());c&&c.Pv(a,b)});
var o0={},p0=null;g.Va(r0,g.po);g.k=r0.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.Kc())return!1;q0(this);this.startTime=a=g.Ua();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.BC();this.Bj("play");-1==this.j&&this.Bj("resume");this.j=1;var b=g.Ra(this);b in o0||(o0[b]=this);zVa();AVa(this,a);return!0};
g.k.stop=function(a){q0(this);this.j=0;a&&(this.progress=1);BVa(this,this.progress);this.Bj("stop");this.Vy()};
g.k.pause=function(){this.Kc()&&(q0(this),this.j=-1,this.Bj("pause"))};
g.k.ea=function(){0==this.j||this.stop(!1);this.Bj("destroy");r0.He.ea.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.NE=function(){this.Bj("animate")};
g.k.Bj=function(a){this.dispatchEvent(new CVa(a,this))};
g.Va(CVa,g.Ce);g.Va(s0,r0);s0.prototype.C=function(){};
s0.prototype.NE=function(){this.C();s0.He.NE.call(this)};
s0.prototype.Vy=function(){this.C();s0.He.Vy.call(this)};
s0.prototype.BC=function(){this.C();s0.He.BC.call(this)};
g.Va(t0,s0);t0.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(u0,g.I);u0.prototype.Ma=function(a,b,c,d){c=(0,g.Sa)(c,d||this.u);a=g.ht(a,b,c);this.j.push(a);return a};
u0.prototype.lC=function(a,b,c,d){c=(0,g.Sa)(c,d||this.u);a=g.Jpa(a,b,c);this.j.push(a);return a};
u0.prototype.vc=function(a){g.jt(a);g.bc(this.j,a)};
u0.prototype.ea=function(){g.jt(this.j);this.j.length=0;g.I.prototype.ea.call(this)};g.w(y0,g.WI);g.k=y0.prototype;g.k.load=function(){g.WI.prototype.load.call(this);if(!z0(this)){var a=g.Txa(this.player.getVideoData());a?(a=x0(a,EVa(this)),A0(this,a,!1)):FVa(this)}};
g.k.unload=function(){A0(this,null);this.B&&(this.B.abort(),this.B=null);g.WI.prototype.unload.call(this)};
g.k.Zf=function(a,b){return z0(this)?"loadCustomEndscreenRenderer"===a?(a=x0(b,"new"),A0(this,a),!0):null:null};
g.k.getOptions=function(){return z0(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.wb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<MWa.length;f++){var h=Math.abs(b.width-MWa[f]);if(-1===e||d>=h)e=f,d=h}d=NWa[e];this.u&&g.al(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.kl(e.element,m,f);g.gl(e.element,n,p);this.W&&(g.ho(e.element,OWa),256<m||256<f?g.N(e.element,"ytp-ce-large-round"):96<m||96<f?g.N(e.element,"ytp-ce-medium-round"):g.N(e.element,"ytp-ce-small-round"));g.ho(e.element,PWa);m=h.left+h.width/2;h=h.top+l/2;g.N(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.ho(e.element,NWa);g.N(e.element,d);(e=g.pg(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.al(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())H0(this,this.endscreen.impressionUrls),(a=g.Lu())&&this.endscreen.visualElement&&g.Qu(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.N(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.N(b,"ytp-ce-shown");H0(this,c.impressionUrls);(b=g.Lu())&&g.Qu(b,c.visualElement);this.player.S().B&&this.player.La("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.go(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.go(b,"ytp-ce-shown");this.player.S().B&&this.player.La("endscreenelementhidden",a)}};
g.k.L_=function(a){var b=this;a.target===window&&(new g.K(function(){for(var c=g.r(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.ho(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var MWa=[346,426,470,506,570,640,853,1280,1920],NWa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),PWa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],OWa=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var PVa={Y6:"current",hda:"new"};var RVa={CLOSE:"close",Bda:"openUrl",SUBSCRIBE:"subscribe"},SVa={H3:"click",CLOSE:"close",E8:"hidden",mfa:"rollOut",nfa:"rollOver",nga:"shown"};var IWa={C2:"anchored",tS:"branding",CHANNEL:"channel",X6:"cta",H8:"highlightText",o$:"label",PLAYLIST:"playlist",xea:"popup",Ega:"speech",SUBSCRIBE:"subscribe",gha:"title",VIDEO:"video",Mia:"website"},HWa={tS:"branding",u3:"card",s7:"drawer",G8:"highlight",Zaa:"marker",Hea:"promotion",TEXT:"text",rja:"widget"};g.w(Q0,g.I);g.k=Q0.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.Av(a,b,{id:c,namespace:"annotations_module"});d&&this.Sa.set(a,d);e&&this.Ta.set(a,e);this.context.G.Vd([a])};
g.k.Dz=function(){this.context.u.subscribe("resize",this.OA,this)};
g.k.OE=function(a,b,c,d,e,f){if(this.kb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Dg(this.element)};
g.k.OA=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=J0(a);if(f){var h=aWa(f,a.target),l=function(){a.j&&e.context.G.pauseVideo();var m=e.context.videoData.D||!1,n=g.bq(f||"");m&&n&&(n.v||n.list)?e.context.G.vl(n.v,b,n.list,!1):g.HH(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);f1(this.context.logger,c,l,d);$Va(f)||(c=g.Lu(),d=b.itct,c&&d&&g.Vu(c,g.Eu(d)))}};
g.k.ea=function(){this.Sa.clear();this.Ta.clear();g.I.prototype.ea.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.J(this,a);return a.element};g.w(V0,Q0);g.k=V0.prototype;g.k.Ep=function(){this.Y&&W0(this,this.Y)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.ll(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.OA=function(){var a=this.isAvailable();g.ml(this.element,a);g.O(this.context.G.getRootNode(),g.zO.IV_DRAWER_ENABLED,a);m0(this.G)};
g.k.destroy=function(){this.G.Pv(!1);try{this.G.getRootNode().removeChild(this.C)}catch(a){}g.Et(this.W);g.jt(this.ma);this.Pa&&this.Pa.dispose();this.D&&this.D.dispose();Q0.prototype.destroy.call(this)};
g.k.AV=function(){if(this.B){f1(this.context.logger,$0(this).tracking.close);var a=g.Lu();a&&this.J&&g.Vu(a,this.J);U0(this)}};
g.k.NV=function(){g.O(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.mX=function(){var a=g.Lu(),b=$0(this);b=b?b.jf:this.jf;a&&b&&g.Tu(a,[b])};
g.k.lX=function(){var a=g.Lu(),b=$0(this);b=b?b.jf:this.jf;a&&b&&g.Uu(a,[b])};
g.k.uU=function(){var a=$0(this);f1(this.context.logger,a.tracking.BR);var b=g.Lu();b&&a&&g.Tu(b,[a.jj,a.jf])};
g.k.nX=function(){var a=g.Lu(),b=$0(this);a&&b&&g.Uu(a,[b.jj])};
g.k.tU=function(a){var b=$0(this),c=g.Lu();this.j?a?(a=this.context.logger,f1(a,b.tracking.BD),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.jj&&g.Vu(c,b.jj)):(a=this.context.logger,f1(a,b.tracking.BD),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.jf&&g.Vu(c,b.jf)):(a=this.context.logger,f1(a,b.tracking.BD),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.jf&&g.Vu(c,this.jf))};g.w(a1,Q0);a1.prototype.Dz=function(){Q0.prototype.Dz.call(this);pWa(this)};
a1.prototype.show=function(){Q0.prototype.show.call(this);var a=g.Lu(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Tu(a,[g.Eu(b.itct)])};
a1.prototype.hide=function(){Q0.prototype.hide.call(this);var a=g.Lu(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Uu(a,[g.Eu(b.itct)])};g.w(b1,a1);
b1.prototype.show=function(){if(!this.isActive){a1.prototype.show.call(this);if(!this.J){g.N(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({F:"img",Ba:["branding-img","iv-click-target"],T:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.ml(this.u,!1);var b=this.context.U.K("html5_player_branding_button_killswitch")?this.createElement({F:"div",Ba:["branding-img-container"]}):this.createElement({F:"button",Ba:["branding-img-container",
"ytp-button"]});b.appendChild(this.u);this.element.appendChild(b);var c=WVa(this.annotation);c&&(b=this.context.U.K("html5_player_branding_button_killswitch")?this.u:b,R0(this,b,c,this.annotation.id,a.session_data));tWa(this,a);this.J=!0}g.ml(this.element,!0);this.isActive=!0;this.u&&qWa(this,this.u)}};
b1.prototype.hide=function(){this.isActive&&(a1.prototype.hide.call(this),g.ml(this.element,!1),this.isActive=!1)};
b1.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);a1.prototype.destroy.call(this)};g.w(c1,a1);g.k=c1.prototype;g.k.show=function(){this.isActive||(a1.prototype.show.call(this),this.V||(vWa(this),this.V=!0),g.ml(this.element,!0),g.$g(function(){g.go(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,e1(this),wWa(this),xWa(this,this.I))};
g.k.hide=function(){this.isActive&&(g.N(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.OE=function(a,b,c,d,e,f){return this.isCollapsed?!1:a1.prototype.OE.call(this,a,b,c,d,e,f)};
g.k.tW=function(a){this.N=!0;d1(this,500,a)};
g.k.sW=function(){this.N=!1;yWa(this)};
g.k.nW=function(a){a.stopPropagation();this.hide()};
g.k.oW=function(a){a.stopPropagation();e1(this);this.isCollapsed=!0;g.N(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();a1.prototype.destroy.call(this)};g.w(g1,g.WI);g.k=g1.prototype;g.k.Zf=function(a,b){if(!LWa(this.player.S().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.EZ(b))&&h1(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(fWa(this.j,b),m0(this.player)),!0}return null};
g.k.getOptions=function(){return LWa(this.player.S().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Ms=function(){var a=this.player.S(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.LQ||a.W.get(b.videoId)||g.QD(b)||g.RD(b)?!0:!1};
g.k.FC=function(){if(this.B){var a=this.player.Ya().getVideoContentRect(!0);g.kl(this.B.element,a.width,a.height);g.gl(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Dj();a=this.j;b=b.width;g.O(a.C,"iv-drawer-small",426>=b);g.O(a.C,"iv-drawer-big",1280<=b)}};
g.k.vU=function(a){BWa(this,a.state);g.V(a.state,2)&&(this.Vh()&&this.Ul()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Pv(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.jq(h)&&h.responseXML?h.responseXML:null)&&(h1(b,h),g.N(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.WI.prototype.load.call(this);BWa(this,this.player.xb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.or()&&(a=DWa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.S().W.get(d);f&&EWa(e,f);f=f&&(f.TA||f.qx);if(!c.fn||f)c.Sa?this.C=g.pq(c.Sa,e):(this.Om=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.Om));
g.II(this.player,this.B.element,4);this.FC();(f=g.QD(c))&&JWa(this,f);(f=g.RD(c))&&f.featuredChannel&&KWa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Sa&&(this.Om&&(this.player.removeEventListener("videodatachange",this.Om),this.Om=null),this.C=g.pq(b.Sa,a))};
g.k.unload=function(){this.player.Df("annotations_module");for(var a=g.r(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.j&&(this.j.destroy(),this.j=null,m0(this.player));this.C&&(this.C.abort(),this.C=null);this.I={};this.u.hide();g.WI.prototype.unload.call(this);this.B.detach();this.Om&&(this.player.removeEventListener("videodatachange",this.Om),this.Om=null)};
g.k.mQ=function(a){a===this.player.getVideoData().videoId&&(this.loaded?FWa(this):this.load())};
g.k.Vh=function(){return!!this.j&&this.j.isAvailable()};
g.k.Ul=function(){return!!this.j&&this.j.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Vh();this.j&&(a?c?T0(this.j,c,b):T0(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):U0(this.j))};
g.k.Pv=function(a,b){this.player.X(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ea=function(){this.player.S().W.unsubscribe("vast_info_card_add",this.mQ,this);g.go(this.player.getRootNode(),g.zO.IV_DRAWER_OPEN);for(var a=this.N,b=g.Bn,c=0,d=a.length;c<d;c++)b.zj(a[c]);this.N.length=0;g.WI.prototype.ea.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.J(this,a);return a.element};g.VI("annotations_module",g1);g.VI("creatorendscreen",y0);})(_yt_player);
