(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var X2=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");-1===c&&(c=a.length);var d="-"===a[0]?"-":"";d&&(a=a.substring(1));return d+(0,g.CTa)("0",Math.max(0,b-c))+a},tYa=function(){return{F:"svg",
T:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},R:[{F:"path",T:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},uYa=function(){return{F:"svg",
T:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},R:[{F:"path",T:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},Z2=function(a){"number"===typeof a?(this.date=vYa(a,0,1),Y2(this,1)):g.Pa(a)?(this.date=vYa(a.getFullYear(),a.getMonth(),a.getDate()),Y2(this,a.getDate())):(this.date=new Date(g.Ua()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),Y2(this,a))},vYa=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},Y2=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},$2=function(a,b){g.HJ.call(this,a,{F:"div",
L:"ytp-reminder-menu",T:{role:"menu",tabindex:"-1"},R:[{F:"div",L:"ytp-reminder-menu-contents",R:[{F:"div",L:"ytp-reminder-menu-items"}]}]},100,!0);this.buttonElement=b;this.j=[];this.menuPopupRenderer=void 0;this.items=this.ya("ytp-reminder-menu-items");this.hide()},xYa=function(a){var b=wYa(a),c=0,d={};
for(c=0;c<b.length;d={TD:d.TD},c++){var e=a.j[c];e||(e=new g.W({F:"div",L:"ytp-reminder-menu-item",T:{role:"menuitem",tabindex:"0"},R:[{F:"div",L:"ytp-reminder-menu-item-icon",Z:"{{icon}}"},{F:"div",L:"ytp-reminder-menu-item-label",Z:"{{text}}"}]}),d.TD=c,e.Ma("click",function(l){return function(){var m=l.TD;a.Gb();m=wYa(a)[m];a.X("reminderMenuItemClicked",m.serviceEndpoint||m.command)}}(d)),e.xa(a.items),a.j[c]=e);
var f=b[c],h=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":h=tYa();break;case "NOTIFICATIONS_NONE":h=uYa();break;case "NOTIFICATIONS_ACTIVE":h=g.HG()}f=f.text?g.Hv(f.text):"";e.update({icon:h,text:f})}for(;c<a.j.length;)a.j.pop().dispose();0===c?a.Gb():a.td(a.buttonElement)},wYa=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},a3=function(a){g.W.call(this,{F:"div",
R:[{F:"button",Ba:["ytp-offline-slate-button","ytp-button"],R:[{F:"div",L:"ytp-offline-slate-button-icon",Z:"{{icon}}"},{F:"div",L:"ytp-offline-slate-button-text",Z:"{{text}}"}]}]});this.G=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.u=void 0;this.C=this.j=null;(this.buttonElement=this.ya("ytp-offline-slate-button"))&&this.P(this.buttonElement,"click",this.D);this.hide()},yYa=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=
b.toggleButtonRenderer:b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&c.upcomingEventReminderButtonRenderer?a.upcomingEventReminderButtonRenderer=c.upcomingEventReminderButtonRenderer:c&&c.upcomingEventReminderButtonRenderer||(a.upcomingEventReminderButtonRenderer=null);b3(a)},b3=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.Hv(b.toggledText):"";a.update({text:c,icon:c3(b.toggledIcon)})}else c=b.defaultText?g.Hv(b.defaultText):"",a.update({text:c,icon:c3(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=zYa(a))?(c=b.text?g.Hv(b.text):"",a.update({text:c,icon:c3(b.icon)}),a.show()):a.hide():a.hide()},BYa=function(a,b,c){a.C||(a.C=new g.bt(a.G.S().Xh));
var d={context:g.hr(a.C.config_||g.gr())};g.Lu()&&(d.context.clientScreenNonce=g.Lu());d.params=c;g.ct(a.C,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.u&&(a.upcomingEventReminderButtonRenderer.currentState=a.u,a.u=void 0)},
onError:function(){AYa(a)},
onTimeout:function(){AYa(a)}})},AYa=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,b3(a)):a.upcomingEventReminderButtonRenderer&&(a.u=void 0,b3(a))},c3=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return tYa();case "NOTIFICATIONS_NONE":return uYa();case "NOTIFICATIONS_ACTIVE":return g.HG();default:return null}},zYa=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.u||a.upcomingEventReminderButtonRenderer.currentState;a=g.r(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=c.value.upcomingEventReminderButtonStateRenderer)&&c.state===b&&c.button&&c.button.buttonRenderer)return c.button.buttonRenderer;return null},d3=function(a){g.W.call(this,{F:"div",
L:"ytp-offline-slate",R:[{F:"div",L:"ytp-offline-slate-background"},{F:"div",L:"ytp-offline-slate-bar",R:[{F:"span",L:"ytp-offline-slate-icon",R:[{F:"svg",T:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},R:[{F:"path",T:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{F:"circle",T:{cx:"12",cy:"12",r:"3"}}]}]},{F:"span",L:"ytp-offline-slate-messages",R:[{F:"div",L:"ytp-offline-slate-main-text",T:{"aria-label":"{{label}}"},Z:"{{mainText}}"},{F:"div",L:"ytp-offline-slate-subtitle-text",Z:"{{subtitleText}}"}]},{F:"span",L:"ytp-offline-slate-buttons"}]},{F:"button",Ba:["ytp-offline-slate-close-button","ytp-button"],R:[g.CG()]},{F:"button",Ba:["ytp-offline-slate-open-button","ytp-button"],R:[g.BG()]},{F:"div",L:"ytp-offline-slate-trailer-chip",Z:"Trailer"}]});var b=
this;this.api=a;this.j=this.u=null;this.background=this.ya("ytp-offline-slate-background");this.B=this.ya("ytp-offline-slate-bar");this.D=new g.K(function(){g.N(b.B,"ytp-offline-slate-bar-fade")},15E3);
this.I=!1;this.C=new g.K(function(){g.N(b.element,"ytp-offline-slate-collapsed")},15E3);
g.J(this,this.C);g.J(this,this.D);this.countdownTimer=new g.K(this.WR,1E3,this);this.P(a,"presentingplayerstatechange",this.aS);this.P(a,"livestatedata",this.Ea);a=this.ya("ytp-offline-slate-close-button");this.P(a,"click",function(){g.N(b.element,"ytp-offline-slate-collapsed")});
a=this.ya("ytp-offline-slate-open-button");this.P(a,"click",function(){g.go(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.Ea(a);a=8===this.api.getPresentingPlayerType()&&!this.getVideoData().Zj;var c=8===this.api.getPresentingPlayerType();g.O(this.element,"ytp-offline-slate-premiere-trailer",a);g.O(this.element,"ytp-offline-slate-hide-background",c)},e3=function(a,b,c){if(b){var d=null!=b.subtitleText?g.Hv(b.subtitleText):"";
c=c?c:null!=b.mainText?g.Hv(b.mainText):"";var e,f,h,l;b=null!=(l=null==(e=b.mainText)?void 0:null==(f=e.accessibility)?void 0:null==(h=f.accessibilityData)?void 0:h.label)?l:c;a.update({mainText:c,subtitleText:d,label:b});g.O(a.element,"ytp-offline-slate-single-text-line",!d);g.O(a.B,"ytp-offline-slate-bar-hidden",!c&&!d)}},f3=function(a,b){var c=(0,g.R)();
this.trigger=a;this.j=b;this.B=c},h3=function(a){g.WI.call(this,a);
var b=this;this.J=!1;this.N=0;this.D=!1;this.u=new g.K(function(){var e=b.player.S(),f=b.getVideoData();g3(b)&&(CYa(b)?DYa(b,e,f):(EYa(b),FYa(b,e,f)))},0);
this.j=this.heartbeatParams=null;this.C=!1;this.I=new g.vh(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.W=new g.bt(void 0);this.V=this.attestationResponse=void 0;this.utcOffsetMinutes=-(new Z2).getTimezoneOffset();this.B=new g.kz(this);g.J(this,this.u);g.J(this,this.B);EYa(this);GYa(this);this.B.P(a,"heartbeatparams",this.Wy);this.B.P(a,"presentingplayerstatechange",this.KU);this.B.P(a,"videoplayerreset",this.LU);this.B.P(a,g.Cv("heartbeat"),this.onCueRangeEnter);this.C&&this.j&&HYa(this,
this.j);var c=new g.Av(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),d=new g.Av(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});a.Vd([c,d]);IYa(this)},IYa=function(a){var b=a.getVideoData();
b.oi&&(b=b.botguardData)&&g.kI(b,a.player.S())},EYa=function(a){var b=a.getVideoData();
if(b.oi&&(b=new g.nCa(b),g.gI.isInitialized()||3<=a.sequenceNumber)){var c=null;if(b.videoData.Ta){var d=g.oCa(b);if(d){c={};var e={};d=d.split("&");d=g.r(d);for(var f=d.next();!f.done;f=d.next())f=f.value.split("="),2===f.length&&(e[f[0]]=f[1]);e.r1a&&(c.webResponse=e.r1a);e.r1c&&(c.error=JYa[Number(e.r1c)]);c.challenge=b.videoData.Ta}}a.attestationResponse=c||void 0}},CYa=function(a){var b=a.getVideoData();
if(!g.FD(a.getVideoData())||b.yK)return!1;if(b.useInnertubeDrmService()&&b.V){a="playready"===b.V.flavor&&b.K("html5_innertube_heartbeats_for_playready");var c="widevine"===b.V.flavor&&b.K("html5_innertube_heartbeats_for_widevine");b=g.dA(b.V)&&b.K("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},i3=function(a){if(CYa(a))return!!a.heartbeatParams;
var b=a.player.S(),c=a.getVideoData();return b.K("html5_heartbeat_wait_for_drm_killswitch")||!g.FD(a.getVideoData())||!c.useInnertubeDrmService()||c.Th||c.zH?!!c.heartbeatToken:!1},j3=function(a,b){if(!a.u.isActive()&&a.J){var c=a.getVideoData();
if(i3(a)||c.isLivePlayback){if(void 0===b)if(a.D)if(a.C)b=7500;else{var d;b=(null==(d=a.heartbeatParams)?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().uK||6E4}else b=1E3;a.u.start(b)}}},NYa=function(a,b,c){b.vk&&(c=g.Mh(c,{internalipoverride:b.vk}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.Kb&&(d.kpt=b.Kb);c=g.Mh(c,d);g.pq(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.u.isActive()&&g3(a)){a.I.reset();a.sequenceNumber++;e=e.responseText;var f=KYa(e);if(f){a.player.La("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(LYa))?"0"===h[1]?0:1:-1;MYa(a,f,e,h)}},
onError:function(e){g3(a)&&k3(a,!0,"net-"+e.status)},
onTimeout:function(){g3(a)&&k3(a,!0,"timeout")},
withCredentials:!0})},DYa=function(a,b,c){var d;
if(null!=(d=a.heartbeatParams)&&d.url){var e=g.Mh(a.heartbeatParams.url,{request_id:g.Pqa()});c.Pa&&(e=g.Mh(e,{vvt:c.Pa}),c.mdxEnvironment&&(e=g.Mh(e,{mdx_environment:c.mdxEnvironment})));g.cC(b,c.oauthToken).then(function(f){f&&(e=g.Mh(e,{access_token:f}));NYa(a,c,e)})}},g3=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.V(a.player.xb(a.getPlayerType()),4)?!1:i3(a)||b.isLivePlayback?!0:(l3(a),!1)},FYa=function(a,b,c){var d,e={videoId:c.videoId,
sequenceNumber:a.sequenceNumber,heartbeatServerData:null!=(d=a.Y)?d:c.heartbeatServerData};a.V=a.attestationResponse;c.oi&&(e.attestationResponse=a.V);var f=g.pI(c),h;d=null!=(h=f.client)?h:{};d.utcOffsetMinutes=a.utcOffsetMinutes;e.context=f;e.cpn=c.clientPlaybackNonce;if(h="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)d.timeZone=h;h={heartbeatChecks:[]};if(d=c.getPlayerResponse())c.heartbeatToken&&(e.heartbeatToken=c.heartbeatToken),(d=d.playabilityStatus)&&
(d=d.liveStreamability)&&d.liveStreamabilityRenderer&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.UB(b)){h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");f=OYa(a);d={};null!==f&&(d.clientPlayerPositionUtcMillis=f);var l,m;f=(null==(m=null==(l=a.player.ib())?void 0:g.kJ(l))?void 0:m.freePreviewWatchedDuration)||0;0<f&&(d.freePreviewWatchedDuration={seconds:""+f});h.unpluggedParams=d}e.heartbeatRequestParams=
h;b.K("enable_linear_player_handling")&&c.isLivePlayback&&(l=OYa(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={utcTimeMillis:l}));var n={timeout:3E4,onSuccess:function(p){if(!a.u.isActive()&&g3(a)){var q=a.getVideoData(),t=q.oi&&null==a.V,u;q.oi=!(null==(u=p.heartbeatAttestationConfig)||!u.requiresAttestation)||t;q=p.playabilityStatus;t=JSON.stringify(q)||"{}";p.authenticationMismatch&&a.player.ra("authshear",{});u=-1;var x=p.playabilityStatus;x&&(a.player.La("onHeartbeat",
x),"OK"===x.status?u=p.stopHeartbeat?2:0:"UNPLAYABLE"===x.status?u=1:"LIVE_STREAM_OFFLINE"===x.status&&(u=0));a.sequenceNumber&&-1===u||a.I.reset();a.sequenceNumber++;p.heartbeatServerData&&(a.Y=p.heartbeatServerData);MYa(a,q,t,u)}},
onError:function(p){g3(a)&&k3(a,!0,"net-"+p.status)},
onTimeout:function(){g3(a)&&k3(a,!0,"timeout")}};
g.cC(b,g.WD(c)).then(function(p){p&&(n.BM="Bearer "+p);g.ct(a.W,"player/heartbeat",e,n)})},MYa=function(a,b,c,d){-1===d?(b="decode "+g.Dc(c),k3(a,!1,b)):2===d?(l3(a),a.D=!0):(a.N=0,a.u.stop(),1===d?(a.D=!1,a.player.qg("heartbeat.stop",2,a.rf(c)),g.vr("heartbeatActionPlayerHalted",PYa(b))):(a.D=!0,c=0,a.C&&b&&(c=HYa(a,b),a.player.X("livestatedata",b)),c?j3(a,c):j3(a)))},HYa=function(a,b){var c=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,d=!(!c||!(c.switchStreamsImmediately||
c.transitionTiming&&"STREAM_TRANSITION_TIMING_IMMEDIATELY"===c.transitionTiming)),e=QYa(c),f=a.getVideoData(),h=a.player.xb(a.getPlayerType()),l=h.Kc()&&!g.KD(f)&&!a.player.isAtLiveHead(a.getPlayerType());
if(2<=f.S().V){var m,n=(null==(m=a.player.Hd())?void 0:m.Nb())||{};n.status=b.status||"";n.dvr=""+ +l;n["switch"]=""+ +d;n.ended=""+ +!(!c||!c.displayEndscreen);a.player.ra("heartbeat",n)}if(l&&!d)return e;d=c&&c.streamTransitionEndpoint&&c.streamTransitionEndpoint.watchEndpoint;if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(c&&c.transitionTiming))a.getVideoData().vP=d;else{if(l=d)(l=d&&d.videoId)?(a.player.vl(l,{autonav:"1"},void 0,!0,!0,d,g.WD(a.getVideoData())),a.mC("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE",
"HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",b),l=!0):l=!1;if(l)return e}if("OK"===b.status.toUpperCase()){d=c&&c.broadcastId;l=a.j&&a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer&&a.j.liveStreamability.liveStreamabilityRenderer.broadcastId;m=d!==l&&(null!=d||a.player.K("web_player_heartbeat_undefined_killswitch"));if(!f.hlsvp&&!f.qb||m){var p={video_id:f.videoId};f.gK&&(p.is_live_destination="1");a.player.K("web_player_heartbeat_request_watch_next")||
(p.disable_watch_next=!0,p.raw_watch_next_response=f.watchNextResponse);p.autonav_state=f.autonavState;p.oauth_token=f.oauthToken;p.force_gvi=f.Xh;p.Hj=f.Hj;c=void 0;f.hlsvp||f.qb?m&&(c=new f3("broadcastIdChanged",l+","+d),a.mC("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",b)):(d&&(c=new f3("formatsReceived",""+d)),a.mC("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",b));a.player.loadVideoByPlayerVars(p,
void 0,void 0,void 0,c);return e}a.player.lf("heartbeat",a.getPlayerType())}c&&c.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.I=!0,a.ob&&a.api.Sv()):g.HF(h)&&(f=(null==(p=a.player.Hd())?void 0:p.Nb())||{},a.player.ra("hbse",f,!0),a.player.Sv(),a.player.La("onLiveMediaEnded",b)));return e},QYa=function(a){var b=0;
a&&a.pollDelayMs&&(a=Number(a.pollDelayMs))&&(b=a);return b},k3=function(a,b,c){var d=a.player.S();
if(!a.u.isActive()){a.u.stop();a.N++;var e=b?"heartbeat.net":"heartbeat.servererror";var f=a.getVideoData();if(f.wK||b&&!g.FD(a.getVideoData())&&!i3(a)&&f.isLivePlayback)f=!1;else{var h,l;(null==(l=a.heartbeatParams)?0:l.Mv)?h=a.heartbeatParams.Mv:h=f.vK||5;f=a.N>=h}f?(g.vr("heartbeatActionPlayerHalted",b?{enforcedPolicyToHaltOnNetworkFailure:!0}:PYa()),(b=a.getVideoData())&&b.isLivePlayback?a.player.qg(e,1,"Video playback interrupted. Please try again.",c):a.player.qg(e,1,"Sorry, there was an error licensing this video.",
c)):(d.K("html5_report_non_fatal_heartbeat_error")&&a.player.zo(e,{msg:c}),j3(a,a.I.getValue()),g.wh(a.I))}},PYa=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},l3=function(a){a.N=0;
a.u.stop();a.D=!1;a.sequenceNumber=0},GYa=function(a){var b=a.getVideoData(),c=a.player.S();
if(b.isLivePlayback)if(g.lA(c.u)){a.C=!0;a.J=!0;if(!g.oB(c)||g.UB(c))a.offlineSlate=new d3(a.player),g.J(a,a.offlineSlate),g.II(a.player,a.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(a.j=b.playabilityStatus);var d;if("UNPLAYABLE"!==(null==(d=a.j)?void 0:d.status)||a.player.K("stop_heartbeat_on_unplayable_live_videos_killswitch"))a.j?(d=QYa(a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer))?j3(a,d):j3(a,7500):j3(a,1E3)}else a.player.qg("html5.unsupportedlive",
2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");else!c.K("html5_release_post_live_heartbeat_killswitch")&&g.Xb(b.oa,"heartbeat")&&a.player.lf("heartbeat",a.getPlayerType())},OYa=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(1E3*a):null},KYa=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},JYa=["ATTESTATION_ERROR_UNKNOWN",
"ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],RYa={L7:["BC","AD"],K7:["Before Christ","Anno Domini"],dda:"JFMAMJJASOND".split(""),Jga:"JFMAMJJASOND".split(""),fca:"January February March April May June July August September October November December".split(" "),Iga:"January February March April May June July August September October November December".split(" "),Lfa:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
Lga:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),mja:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),Nga:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),lga:"Sun Mon Tue Wed Thu Fri Sat".split(" "),Mga:"Sun Mon Tue Wed Thu Fri Sat".split(" "),eda:"SMTWTFS".split(""),Kga:"SMTWTFS".split(""),Mfa:["Q1","Q2","Q3","Q4"],Nea:["1st quarter","2nd quarter","3rd quarter","4th quarter"],z2:["AM","PM"],a7:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],
eha:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],b7:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],HS:6,nja:[5,6],IS:5},m3=RYa;m3=RYa;g.k=Z2.prototype;g.k.AN=m3.HS;g.k.BN=m3.IS;g.k.clone=function(){var a=new Z2(this.date);a.AN=this.AN;a.BN=this.BN;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getYear=function(){return this.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.getTime=function(){return this.date.getTime()};
g.k.getDay=function(){return this.date.getDay()};
g.k.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.k.getUTCMonth=function(){return this.date.getUTCMonth()};
g.k.getUTCDate=function(){return this.date.getUTCDate()};
g.k.getUTCDay=function(){return this.date.getDay()};
g.k.getUTCHours=function(){return this.date.getUTCHours()};
g.k.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.k.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.setFullYear=function(a){this.date.setFullYear(a)};
g.k.setYear=function(a){this.setFullYear(a)};
g.k.setMonth=function(a){this.date.setMonth(a)};
g.k.setDate=function(a){this.date.setDate(a)};
g.k.setTime=function(a){this.date.setTime(a)};
g.k.setUTCFullYear=function(a){this.date.setUTCFullYear(a)};
g.k.setUTCMonth=function(a){this.date.setUTCMonth(a)};
g.k.setUTCDate=function(a){this.date.setUTCDate(a)};
g.k.add=function(a){if(a.u||a.j){var b=this.getMonth()+a.j+12*a.u,c=this.getYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.days&&(c=this.getYear(),b=0<=c&&99>=c?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.setDate(1),this.setFullYear(a.getFullYear()+
b),this.setMonth(a.getMonth()),this.setDate(a.getDate()),Y2(this,a.getDate()))};
g.k.equals=function(a){return!(!a||this.getYear()!=a.getYear()||this.getMonth()!=a.getMonth()||this.getDate()!=a.getDate())};
g.k.toString=function(){var a=this.getFullYear(),b=0>a?"-":1E4<=a?"+":"";return[b+X2(Math.abs(a),b?6:4),X2(this.getMonth()+1,2),X2(this.getDate(),2)].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};g.w($2,g.HJ);$2.prototype.hide=function(){this.buttonElement&&this.buttonElement.removeAttribute("aria-haspopup");g.HJ.prototype.hide.call(this)};
$2.prototype.show=function(){this.buttonElement&&this.buttonElement.setAttribute("aria-haspopup","true");g.HJ.prototype.show.call(this)};
$2.prototype.ea=function(){g.Ae(this.j);g.HJ.prototype.ea.call(this)};g.w(a3,g.W);
a3.prototype.D=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.B(a.toggledServiceEndpoint):this.B(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;b3(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.j&&this.j.ob)this.j.Gb();else{var b=zYa(this);b&&this.B(b.serviceEndpoint||b.command);b=g.r(b&&b.command&&b.command.commandExecutorCommand&&b.command.commandExecutorCommand.commands||[]);for(var c=b.next();!c.done;c=b.next())if((c=c.value)&&c.openPopupAction&&
c.openPopupAction.popup&&c.openPopupAction.popup.menuPopupRenderer){a=c.openPopupAction.popup.menuPopupRenderer;break}this.j||(this.j=new $2(this.G,this.buttonElement),this.j.xa(this.element),g.J(this,this.j),this.j.subscribe("reminderMenuItemClicked",this.B,this));b=this.j;b.menuPopupRenderer=a;xYa(b)}};
a3.prototype.B=function(a){if(a&&(a.addUpcomingEventReminderEndpoint||a.removeUpcomingEventReminderEndpoint)){if(a.addUpcomingEventReminderEndpoint){var b=a.addUpcomingEventReminderEndpoint;var c="notification/add_upcoming_event_reminder"}else a.removeUpcomingEventReminderEndpoint&&(b=a.removeUpcomingEventReminderEndpoint,c="notification/remove_upcoming_event_reminder");if(c&&b&&b.params)for(BYa(this,c,b.params),a=g.r(b.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&b.updateUpcomingEventReminderButtonStateCommand){this.u=
b.updateUpcomingEventReminderButtonStateCommand.state;b3(this);break}}};g.w(d3,g.W);g.k=d3.prototype;g.k.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.Ea=function(a){var b,c,d=null==a?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:c.offlineSlate;if(d){this.u=a;b=d.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.WR():e3(this,b);var e,f,h,l;if(c=null==a?void 0:null==(e=a.liveStreamability)?void 0:null==(f=e.liveStreamabilityRenderer)?void 0:null==(h=f.offlineSlate)?void 0:null==(l=h.liveStreamOfflineSlateRenderer)?void 0:l.thumbnail){e=0;f=null;h=c.thumbnails;for(l=0;l<h.length;l++)h[l].width>e&&
(e=h[l].width||0,f=h[l].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.j||(this.j=new a3(this.api),this.j.xa(this.ya("ytp-offline-slate-buttons")),g.J(this,this.j)),yYa(this.j,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.j&&yYa(this.j,null,null);this.u=a}else this.u=null;this.aS()};
g.k.aS=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.xb(),d=this.getVideoData();b=d.isLivePlayback&&(g.HF(c)||g.V(c,2)||g.V(c,64));var e=2===d.autonavState&&g.V(c,2);c=c.Kc()&&!g.KD(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.u?this.ob?(null==a?0:g.VE(a,2))&&!this.getVideoData().Zj&&(g.go(this.element,"ytp-offline-slate-collapsed"),this.C.stop(),g.go(this.B,"ytp-offline-slate-bar-fade"),this.D.start()):(this.show(),this.C.start(),this.api.X("offlineslatestatechange"),
this.I&&this.api.Sv()):this.ob&&(this.hide(),this.api.X("offlineslatestatechange"))};
g.k.WR=function(){var a,b,c,d,e=null==(a=this.u)?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:null==(d=c.offlineSlate)?void 0:d.liveStreamOfflineSlateRenderer;e&&(a=Math.floor(g.Ua()/1E3),b=e.canShowCountdown&&Number(e.scheduledStartTime),!b||b<=a?(e3(this,e),this.countdownTimer.stop()):(e3(this,e,g.vH(b-a)),g.Fn(this.countdownTimer)))};
g.k.ea=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.W.prototype.ea.call(this)};f3.prototype.u=function(a){return this.trigger&&a.trigger?this.trigger===a.trigger&&this.j===a.j:!1};
f3.prototype.isExpired=function(){return 6E4<(0,g.R)()-this.B};
f3.prototype.toString=function(){return"heartbeat:"+this.trigger+":"+this.j};g.w(h3,g.WI);g.k=h3.prototype;g.k.ea=function(){l3(this);this.player.Df("heartbeat");g.WI.prototype.ea.call(this)};
g.k.onCueRangeEnter=function(){this.J=!0;j3(this,2E3)};
g.k.Wy=function(a){this.heartbeatParams=a;j3(this,2E3)};
g.k.KU=function(a){var b;8===this.player.getPresentingPlayerType()||"UNPLAYABLE"===(null==(b=this.j)?void 0:b.status)&&!this.player.K("stop_heartbeat_on_unplayable_live_videos_killswitch")||(g.V(a.state,2)||g.V(a.state,64)?(l3(this),this.C&&(this.J=!0,j3(this,1E3))):(g.V(a.state,1)||g.V(a.state,8))&&j3(this,2E3))};
g.k.LU=function(){3!==this.player.getPresentingPlayerType()&&j3(this,2E3)};
g.k.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.hj=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.mC=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.vr("heartbeatActionPlayerTransitioned",a)};
g.k.rf=function(a){var b="LICENSE",c=KYa(a);if(c)return c.reason||g.BJ[b]||"";(a=a.match(LYa))&&(a=Number(a[1]))&&(b=g.aza(a));return g.BJ[b]||""};
g.k.yy=function(){return!!this.offlineSlate&&this.offlineSlate.ob};
var LYa=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.VI("heartbeat",h3);})(_yt_player);
